### ISSUE TITLE
Time is not centred when in 12-hour mode

### ISSUE THREAD

**Issue by lepinsk** [Niknam/futura-weather-sdk2.0#4]
Specifically when the hour field is a single-digit.

![pebble-screenshot_2014-02-05_21-43-50](https://f.cloud.github.com/assets/154543/2095824/ba5059e0-8ef1-11e3-9670-886ded32371f.png)

I've fixed this issue in a fork and will (attempt to) kick off a pull request for the fix. Bear with me.

**Comment by Niknam** [comment]
Thanks for noticing this! I'm always in 24-hour mode, so I was unaware of this issue. Will make it a part of the official binary shortly.

**Comment by lepinsk** [comment]
No problem – I figured it was that. Glad to be of assistance – I love this watchface! 

I've tested this out in both modes, and I don't see how I could break something, but I'd advise playing around a bit to be sure I haven't missed anything here...

**Comment by Niknam** [comment]
Will do. Thanks again!

**Comment by Niknam** [comment]
Have been running it since yesterday, and it looks good to me. The fix is now published in the appstore. Thanks again! :)

**Comment by lepinsk** [comment]
Any time. Just happy to help. :-)
